### ISSUE TITLE
Support for Sync between devices?

### ISSUE THREAD

**Issue by brycefisher** [rust-keylock/rust-keylock-android#1]
If I'm running the desktop UI editor and the Android editor, is there builtin support sync between devices? If not, are there any recommended techniques for syncing between various devices?

**Comment by astonbitecode** [comment]
The built-in sync support along with automated backups is planned for the next releases and is not supported currently. 

What I personally do, is using the export/import mechanism along with a synchronization service like nextcloud or dropbox. This is a workaround that involves more hassle, but gets the work done.

**Comment by astonbitecode** [comment]
@brycefisher the next release (v0.4.0) will support syncing via nextcloud/owncloud.

**Comment by astonbitecode** [comment]
Closing this as it is already in the [release 0.4.0](https://github.com/rust-keylock/rust-keylock-android/releases/tag/v0.4.0)
